### ISSUE TITLE
Signing in times out

### ISSUE THREAD

**Issue by sdfg2** [jackyzy823/fxa-selfhosting#13]
I set up everything as in the wonderful documentation.  I'm using my own nginx as a reverse proxy.  All the containers start correctly, and my nginx proxying works (the sign up page shows up).

When I get to the sign in page, I put my email address in and hit the button and it just spins and times out.  The browser console shows these errors:

```
Content Security Policy: Not supporting directive ‘script-src-attr’. Directive and values will be ignored. 2
WebChannel error: No Such Channel logger.js:72:35
WebChannel error: No Such Channel logger.js:72:35
WebChannel error: No Such Channel logger.js:72:35
    error logger.js:72
    _reportError web-channel.js:89
    receiveMessage web-channel.js:72
Working… logger.js:69:29
    error logger.js:69
    captureError error-utils.js:63
    logError base.js:786
    O base.js:80
    Underscore 2
    _workingTimeout notify_delayed_request.js:21
    i timer-mixin.js:29
    (Async: setTimeout handler)
    setTimeout timer-mixin.js:27
    default notify_delayed_request.js:19
    validateAndSubmit form.js:217
    (Async: promise callback)
    validateAndSubmit form.js:197
    invokeHandler base.js:1071
    default allow_only_one_submit.js:24
    (Async: promise callback)
    default allow_only_one_submit.js:24
    onFormSubmit form.js:152
    invokeHandler base.js:1071
    default prevent_default_then.js:19
    jQuery 8
    Backbone 2
    _attachEvents form.js:256
    constructor form.js:59
    M app.bundle.en_US.js:9
    o index.js:40
    createView app.js:14
    showView app.js:103
    (Async: promise callback)
    showView app.js:83
    delegateNotifications notifier-mixin.js:70
    Backbone 4
    showView app-start.js:207
    es user.js:107
    (Async: promise callback)
    es user.js:107
    Backbone 3
    Me Underscore
    Backbone 2
    allResourcesReady app.js:14
    startApp app.js:14
    (Async: promise callback)
    startApp app.js:14
    <anonymous> app.js:14
    (Async: promise callback)
    <anonymous> app.js:14
    Webpack 4
Response not received for: fxaccounts:can_link_account logger.js:72:35
    error logger.js:72
    timeout duplex.js:35
    add duplex.js:33
    request duplex.js:152
    request duplex.js:142
    request app.bundle.en_US.js:9
    (Async: promise callback)
    request app.bundle.en_US.js:9
    beforeSignIn state-machine.js:22
    invokeBrokerMethod base.js:1113
    value index.js:234
    value index.js:143
    _submitForm form.js:239
    (Async: promise callback)
    _submitForm form.js:236
    invokeHandler base.js:1071
    default progress_indicator.js:42
    (Async: promise callback)
    default progress_indicator.js:42
    invokeHandler base.js:1071
    default notify_delayed_request.js:25
    (Async: promise callback)
    default notify_delayed_request.js:25
    validateAndSubmit form.js:217
    (Async: promise callback)
    validateAndSubmit form.js:197
    invokeHandler base.js:1071
    default allow_only_one_submit.js:24
    (Async: promise callback)
    default allow_only_one_submit.js:24
    onFormSubmit form.js:152
    invokeHandler base.js:1071
    default prevent_default_then.js:19
    jQuery 8
```

[I tried working around this](https://github.com/docker/compose/issues/9030) to get the nginx logs, but even after setting every logging driver to `json-file` in `docker-compose.yml` I always just get `Error response from daemon: configured logging driver does not support reading` when running `docker-compose logs`.  I don't run docker usually, but this is one of the few projects where docker makes sense.  Unfortunately, that means I have no idea how to track down problems!

Any advice?

**Comment by jackyzy823** [comment]
Hello , can you provide the HTTP request and its body( error message) from client ( from browser developer console -> Network) especially  non-200 requests.

On server side, can you provide fxa-auth-server's logs?

**Comment by sdfg2** [comment]
Well, in the wonderful way of these things, it now no longer times out!  It spits out an error this time though, 500, which is progress!

The request is `https://api.fxa.mydomain.tld/v1/account/status` (where mydomain is my actual domain).  The response is just a bog standard 500 internal server error.  I checked my reverse proxy, and it's not there.  The fxa-auth-server log shows :

```
dest-fxa-auth-server-1  | {"Timestamp":1664744953015000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":30,"EnvVersion":"2.0","Fields":{"status":500,"errno":999,"path":"/v1/account/status","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Windows NT 10.0; rv:105.0) Gecko/20100101 Firefox/105.0","remoteAddressChain":"[\"10.1.2.3\",\"10.1.0.1\",\"172.19.0.12\"]","t":39,"uid":"00","keys":false,"method":"post","email":"theuser@mydomain.tld"}}
dest-fxa-auth-server-1  | {"Timestamp":1664744953015000000,"Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,"Pid":30,"EnvVersion":"2.0","Fields":{"event":"route./account/status.500.999","missingFlowId":true}}
```

I've only just come back to Firefox after what feels like a thousand years, so apologies if I'm not copying the correct information across.  Also there is still [this error ](https://github.com/docker/compose/issues/9030) happening with every logging driver set to json-file, so I'm not sure how much else I can give you from the docker logs, but I'll try!

**Comment by jackyzy823** [comment]
It's quite wired. `v1/account/status` only checks if domain is valid (not applied here maybe) and whether account is in the db.

I guess the question maybe db related.

Maybe a full `fxa-auth-server` log will help.

**Comment by sdfg2** [comment]
How do I go about getting a full log?  I'm very new to trying to debug docker stuff

**Comment by jackyzy823** [comment]
you can `docker-compose logs fxa-auth-server > /tmp/somepath.log` and check `/tmp/somepath.log`


> I presumed it would check the db, then go 'oops, you don't have an account yet, sign up now'. I don't know how else to sign up.
You're right. 
In the main page , Enter the email address, then click "Continue" ,fxa will check if the account exists, and let you login (account  exists) / sign up (account not exists)

**Comment by sdfg2** [comment]
Doing that, the only thing that shows up for the activity is this:

```
dest-fxa-auth-server-1  | Connection Error: Error: Connection lost: The server closed the connection.
dest-fxa-auth-server-1  | {"Timestamp":1664892338394000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":30,"EnvVersion":"2.0","Fields":{"status":500,"errno":999,"path":"/v1/account/status","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Windows NT 10.0; rv:105.0) Gecko/20100101 Firefox/105.0","remoteAddressChain":"[\"10.1.2.3\",\"10.1.0.1\",\"172.19.0.12\"]","t":39,"uid":"00","keys":false,"method":"post","email":"me@myemail.tld"}}
dest-fxa-auth-server-1  | {"Timestamp":1664892338395000000,"Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,"Pid":30,"EnvVersion":"2.0","Fields":{"event":"route./account/status.500.999","missingFlowId":true}}
```

**Comment by jackyzy823** [comment]
Well, that doesn't help more. 

Could you provide the generated docker-compose.yml and/or config.yml. (Remember to redact your info).

**Comment by sdfg2** [comment]
Sure!

docker-compose.yml

<details></p>

```
version: "3.7"
x-logging:
  options:
    max-size: 5m
    max-file: "3"
  driver: json-file
services:
  mysqldb:
    image: mysql:5.7
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_ROOT_HOST=%
    expose:
    - "3306"
    volumes:
    - ./mysql_data:/var/lib/mysql/
    - ./_init/mysql/init.sql:/tmp/common_init.sql:ro
    logging:
      driver: json-file
    restart: unless-stopped
    command:
    - --event-scheduler=ON
    - --init-file=/tmp/common_init.sql
  redis:
    image: redis:6.0-alpine
    expose:
    - "6379"
    logging:
      driver: json-file
    volumes:
    - type: tmpfs
      target: /data
    restart: unless-stopped
  browseridverifier.local:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/browserid-verifier
    expose:
    - "5050"
    environment:
    - PORT=5050
    - IP_ADDRESS=0.0.0.0
    - FORCE_INSECURE_LOOKUP_OVER_HTTP=false
    - HTTP_TIMEOUT=60
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
    entrypoint: node
    command: server.js
  syncserver:
    image: mozilla/syncserver@sha256:016162bf39d8486d5710b4ae5bcaaebd8bd60b55db6cf468b8f720b526bd68b7
    expose:
    - "5000"
    environment:
    - WAIT_HOSTS=mysqldb:3306,fxa-auth-server:9000,fxa-content-server:3030
    - WAIT_HOSTS_TIMEOUT=120
    - SYNCSERVER_PUBLIC_URL=https://token.fxa.mydomain.tld
    - SYNCSERVER_BROWSERID_VERIFIER=http://browseridverifier.local:5050
    - SYNCSERVER_SQLURI=mysql+pymysql://root@mysqldb/sync
    - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
    - SYNCSERVER_FORCE_WSGI_ENVIRON=true
    - PORT=5000
    - SYNCSERVER_OAUTH_VERIFIER=http://fxa-auth-server:9000
    - SYNCSERVER_IDENTITY_PROVIDER=http://fxa-content-server:3030
    depends_on:
    - mysqldb
    - fxa-auth-server
    - fxa-content-server
    volumes:
    - ./wait:/wait
    entrypoint: sh -c "/wait && /usr/bin/dumb-init /app/docker-entrypoint.sh server"
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  pushbox.local:
    image: mozilla/pushbox:0.3.0
    expose:
    - "8002"
    environment:
    - ROCKET_ENV=prod
    - ROCKET_PORT=8002
    - ROCKET_SERVER_TOKEN=rs7sicRJd4BKzoxDlXcm
    - ROCKET_DATABASE_URL=mysql://root@mysqldb/pushbox
    - WAIT_HOSTS=mysqldb:3306
    - WAIT_HOSTS_TIMEOUT=120
    depends_on:
    - mysqldb
    volumes:
    - ./wait:/wait
    command: sh -c "/wait && /app/bin/pushbox"
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-db-migrations:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/db-migrations
    depends_on:
    - mysqldb
    volumes:
    - ./wait:/wait
    command: sh -c "/wait && node ./bin/patcher.mjs"
    environment:
    - WAIT_HOSTS=mysqldb:3306
    - WAIT_HOSTS_TIMEOUT=120
    - AUTH_MYSQL_HOST=mysqldb
    - PROFILE_MYSQL_HOST=mysqldb
    - OAUTH_MYSQL_HOST=mysqldb
    restart: "no"
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  exim-sender:
    image: elsdoerfer/exim-sender
    environment:
    - ALLOWED_HOSTS="192.168.0.0/16;172.16.0.0/12;10.0.0.0/8"
    - PRIMARY_HOST=fxa.mydomain.tld
    expose:
    - "25"
    volumes:
    - type: tmpfs
      target: /var/spool/exim4
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-auth-server:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/fxa-auth-server/dist/fxa-auth-server
    expose:
    - "9000"
    depends_on:
      redis:
        condition: service_started
      mysqldb:
        condition: service_started
      fxa-db-migrations:
        condition: service_completed_successfully
    volumes:
    - ./wait:/wait
    - ./_init/auth/oauthserver-prod.json:/fxa/packages/fxa-auth-server/dist/fxa-auth-server/config/prod.json
    environment:
    - OAUTH_SERVER_SECRET_KEY=0foI8mXfRNNfOvH082Ll
    - OAUTH_SERVER_SECRETS=0foI8mXfRNNfOvH082Ll
    - AUTH_SERVER_SHARED_SECRET=0foI8mXfRNNfOvH082Ll
    - AUTH_SERVER_SECRETS=0foI8mXfRNNfOvH082Ll,realwhatever
    - SUPPORT_PANEL_AUTH_SECRET_BEARER_TOKEN=58smtPA7WeCYHbNPYiXN
    - PROFILE_SERVER_AUTH_SECRET_BEARER_TOKEN=QNW74kv6WzZgPMAntkWH
    - FLOW_ID_KEY=qaJ9toy6jQ0f2yWXNU8A
    - REDIS_HOST=redis
    - ACCESS_TOKEN_REDIS_HOST=redis
    - REFRESH_TOKEN_REDIS_HOST=redis
    - SNS_TOPIC_ARN=disabled
    - MEMCACHE_METRICS_CONTEXT_ADDRESS=none
    - DB=mysql
    - MYSQL_HOST=mysqldb
    - AUTH_MYSQL_HOST=mysqldb
    - IP_ADDRESS=0.0.0.0
    - SIGNIN_UNBLOCK_FORCED_EMAILS=^block.*@restmail\\.net$$
    - SIGNIN_CONFIRMATION_ENABLED=true
    - SIGNIN_CONFIRMATION_FORCE_EMAIL_REGEX=^sync.*@restmail\\.net$$
    - ISSUER=api.fxa.mydomain.tld
    - PUBLIC_URL=https://api.fxa.mydomain.tld
    - OAUTH_URL=https://oauth.fxa.mydomain.tld
    - CONTENT_URL=https://www.fxa.mydomain.tld
    - CONTENT_SERVER_URL=https://www.fxa.mydomain.tld
    - SYNC_TOKENSERVER_URL=https://token.fxa.mydomain.tld/token
    - PROFILE_SERVER_URL=http://fxa-profile-server:1111
    - FXA_OPENID_ISSUER=https://www.fxa.mydomain.tld
    - VERIFICATION_URL=http://browseridverifier.local:5050/v2
    - PUSHBOX_KEY=rs7sicRJd4BKzoxDlXcm
    - PUSHBOX_URL=http://pushbox.local:8002
    - PUSHBOX_ENABLED=true
    - CUSTOMS_SERVER_URL=none
    - FXA_OPENID_KEYFILE=config/key.json
    - FXA_OPENID_NEWKEYFILE=config/newKey.json
    - FXA_OPENID_OLDKEYFILE=config/oldKey.json
    - SMTP_SENDER=Firefox Accounts <no-reply@fxa.mydomain.tld>
    - SMTP_HOST=exim-sender
    - SMTP_PORT=25
    - SMTP_USER=local
    - SMTP_PASS=local
    - GEODB_ENABLED=false
    - WAIT_HOSTS=redis:6379,mysqldb:3306
    - WAIT_HOSTS_TIMEOUT=120
    - LOG_LEVEL=WARN
    - LASTACCESSTIME_UPDATES_SAMPLE_RATE=1
    command: sh -c "node scripts/gen_keys.js; node scripts/oauth_gen_keys.js ; node
      scripts/gen_vapid_keys.js  && /wait && node bin/key_server.js"
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-profile-static:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/fxa-profile-server
    volumes:
    - ./public:/fxa/packages/fxa-profile-server/var/public/:ro
    expose:
    - "1112"
    environment:
    - HOST=0.0.0.0
    - IMG=local
    command:
    - node
    - bin/_static.js
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-profile-worker-make-writable:
    image: mozilla/fxa-mono:v1.235.1
    user: root
    volumes:
    - ./public:/fxa/packages/fxa-profile-server/var/public/
    command:
    - chmod
    - a+w
    - /fxa/packages/fxa-profile-server/var/public/
    restart: "no"
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-profile-worker:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/fxa-profile-server
    volumes:
    - ./public:/fxa/packages/fxa-profile-server/var/public/
    expose:
    - "1113"
    environment:
    - WORKER_HOST=0.0.0.0
    - IMG=local
    depends_on:
      fxa-profile-worker-make-writable:
        condition: service_completed_successfully
    command:
    - node
    - bin/worker.js
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-profile-server:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/fxa-profile-server
    expose:
    - "1111"
    depends_on:
      mysqldb:
        condition: service_started
      redis:
        condition: service_started
      fxa-db-migrations:
        condition: service_completed_successfully
    environment:
    - WAIT_HOSTS=mysqldb:3306,redis:6379
    - WAIT_HOSTS_TIMEOUT=120
    - AUTH_SECRET_BEARER_TOKEN=QNW74kv6WzZgPMAntkWH
    - EVENTS_ENABLED=false
    - HOST=0.0.0.0
    - DB=mysql
    - IMG_PROVIDERS_FXA=^https://profile.fxa.mydomain.tld/img/a/[0-9a-f]{32}$$
    - IMG_URL=https://profile.fxa.mydomain.tld/img/a/{id}
    - PUBLIC_URL=https://profile.fxa.mydomain.tld
    - MYSQL_HOST=mysqldb
    - IMG=local
    - AUTH_SERVER_URL=http://fxa-auth-server:9000/v1
    - OAUTH_SERVER_URL=http://fxa-auth-server:9000/v1
    - REDIS_HOST=redis
    - WORKER_URL=http://fxa-profile-worker:1113
    volumes:
    - ./wait:/wait
    - ./public:/fxa/packages/fxa-profile-server/var/public/
    command: sh -c "sed -i 's|result.avatar.startsWith(monogramUrl)|result.avatar.startsWith(`$${monogramUrl}/v1/avatar/`)|'  /fxa/packages/fxa-profile-server/lib/routes/profile.js
      && /wait && node bin/server.js"
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-content-server:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/fxa-content-server
    expose:
    - "3030"
    depends_on:
    - fxa-auth-server
    - fxa-profile-server
    - redis
    volumes:
    - ./_init/content/contentserver-prod.json:/fxa/packages/fxa-content-server/config/prod.json
    environment:
    - CONFIG_FILES=/fxa/packages/fxa-content-server/config/prod.json
    - FXA_OAUTH_CLIENT_ID=ea3ca969f8c6bb0d
    - FLOW_ID_KEY=qaJ9toy6jQ0f2yWXNU8A
    - FEATURE_FLAGS_REDIS_HOST=redis
    - SYNC_TOKENSERVER_URL=https://token.fxa.mydomain.tld/token
    - PUBLIC_URL=https://www.fxa.mydomain.tld
    - FXA_OAUTH_URL=https://oauth.fxa.mydomain.tld
    - FXA_URL=https://api.fxa.mydomain.tld
    - FXA_PROFILE_URL=https://profile.fxa.mydomain.tld
    - FXA_PROFILE_IMAGES_URL=https://profile.fxa.mydomain.tld
    - PAIRING_SERVER_BASE_URI=wss://channelserver.fxa.mydomain.tld
    - FXA_MARKETING_EMAIL_ENABLED=false
    - GEODB_ENABLED=false
    - LOG_LEVEL=WARN
    - NODE_ENV=production
    - STATIC_DIRECTORY=dist
    - PAGE_TEMPLATE_SUBDIRECTORY=dist
    - CSP_ENABLED=true
    - FXA_GQL_URL=https://graphql.fxa.mydomain.tld
    - REDIRECT_CHECK_ALLOW_LIST=*.fxa.mydomain.tld
    command:
    - node
    - server/bin/fxa-content-server.js
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  fxa-graphql-api:
    image: mozilla/fxa-mono:v1.235.1
    working_dir: /fxa/packages/fxa-graphql-api
    expose:
    - "8290"
    volumes:
    - ./wait:/wait
    depends_on:
    - fxa-auth-server
    - fxa-profile-server
    - redis
    - mysqldb
    environment:
    - WAIT_HOSTS=mysqldb:3306,redis:6379
    - WAIT_HOSTS_TIMEOUT=120
    - ACCESS_TOKEN_REDIS_HOST=redis
    - PROFILE_SERVER_URL=http://fxa-profile-server:1111/v1
    - CUSTOMS_SERVER_URL=none
    - CORS_ORIGIN=https://www.fxa.mydomain.tld
    - AUTH_SERVER_URL=https://api.fxa.mydomain.tld
    - AUTH_MYSQL_HOST=mysqldb
    - PROFILE_MYSQL_HOST=mysqldb
    - OAUTH_MYSQL_HOST=mysqldb
    command: sh -c "/wait && node dist/main.js"
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
      driver: json-file
  nginx:
    image: nginx:1.22.0-alpine
    ports:
    - 10.1.2.3:1234:80
    depends_on:
    - fxa-auth-server
    - fxa-profile-server
    - syncserver
    - fxa-content-server
    - fxa-graphql-api
    volumes:
    - ./_init/nginx/fxa_nossl.conf.tmpl:/etc/nginx/templates/fxa.conf.tmpl:ro
    - ./_init/nginx/channelserver_nossl.conf.tmpl:/etc/nginx/templates/channelserver.conf.tmpl:ro
    environment:
    - NGINX_LISTENER=80
    - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.tmpl
    - NGINX_DOMAIN_NAME=fxa.mydomain.tld
    - CONTENT=www
    - AUTH=api
    - OAUTH=oauth
    - PROFILE=profile
    - SYNC=token
    - GRAPHQL=graphql
    - CHANNELSERVER=channelserver
    logging:
      driver: json-file
    restart: unless-stopped
  channelserver:
    image: mozilla/channelserver:latest
    expose:
    - "8000"
    restart: unless-stopped
    logging:
      driver: json-file
```

</p></details>

For good luck, my nginx conf for fxa:

<details><p>

```
server  {
	### Logging

	### Core
	listen my.ip.add.ress:443 ssl http2;
	listen 10.1.0.1:443 ssl http2;
	server_name www.fxa.mydomain.tld;

	### TLS
	include /etc/nginx/conf/00-tls-base.conf;
	ssl_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/fxa.mydomain.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;

	### ACL
	include conf/10-acl-mydomain.tld.conf;
	deny all;

	### Bots
	include /etc/nginx/bots.d/ddos.conf;
	include /etc/nginx/bots.d/blockbots.conf;

	### Paths
	location / {
		proxy_pass http://10.1.2.3:1234/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

server  {
	### Logging

	### Core
	listen my.ip.add.ress:443 ssl http2;
	listen 10.1.0.1:443 ssl http2;
	server_name profile.fxa.mydomain.tld;

	### TLS
	include /etc/nginx/conf/00-tls-base.conf;
	ssl_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/fxa.mydomain.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;

	### ACL
	include conf/10-acl-mydomain.tld.conf;
	deny all;

	### Bots
	include /etc/nginx/bots.d/ddos.conf;
	include /etc/nginx/bots.d/blockbots.conf;

	### Paths
	location / {
		proxy_pass http://10.1.2.3:1234/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

server  {
	### Logging

	### Core
	listen my.ip.add.ress:443 ssl http2;
	listen 10.1.0.1:443 ssl http2;
	server_name token.fxa.mydomain.tld;

	### TLS
	include /etc/nginx/conf/00-tls-base.conf;
	ssl_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/fxa.mydomain.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;

	### ACL
	include conf/10-acl-mydomain.tld.conf;
	deny all;

	### Bots
	include /etc/nginx/bots.d/ddos.conf;
	include /etc/nginx/bots.d/blockbots.conf;

	### Paths
	location / {
		proxy_pass http://10.1.2.3:1234/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

server  {
	### Logging

	### Core
	listen my.ip.add.ress:443 ssl http2;
	listen 10.1.0.1:443 ssl http2;
	server_name api.fxa.mydomain.tld;

	### TLS
	include /etc/nginx/conf/00-tls-base.conf;
	ssl_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/fxa.mydomain.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;

	### ACL
	include conf/10-acl-mydomain.tld.conf;
	deny all;

	### Bots
	include /etc/nginx/bots.d/ddos.conf;
	include /etc/nginx/bots.d/blockbots.conf;

	### Paths
	location / {
		proxy_pass http://10.1.2.3:1234/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

server  {
	### Logging

	### Core
	listen my.ip.add.ress:443 ssl http2;
	listen 10.1.0.1:443 ssl http2;
	server_name oauth.fxa.mydomain.tld;

	### TLS
	include /etc/nginx/conf/00-tls-base.conf;
	ssl_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/fxa.mydomain.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;

	### ACL
	include conf/10-acl-mydomain.tld.conf;
	deny all;

	### Bots
	include /etc/nginx/bots.d/ddos.conf;
	include /etc/nginx/bots.d/blockbots.conf;

	### Paths
	location / {
		proxy_pass http://10.1.2.3:1234/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

server  {
	### Logging

	### Core
	listen my.ip.add.ress:443 ssl http2;
	listen 10.1.0.1:443 ssl http2;
	server_name graphql.fxa.mydomain.tld;

	### TLS
	include /etc/nginx/conf/00-tls-base.conf;
	ssl_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/fxa.mydomain.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;

	### ACL
	include conf/10-acl-mydomain.tld.conf;
	deny all;

	### Bots
	include /etc/nginx/bots.d/ddos.conf;
	include /etc/nginx/bots.d/blockbots.conf;

	### Paths
	location / {
		proxy_pass http://10.1.2.3:1234/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

server  {
	### Logging

	### Core
	listen my.ip.add.ress:443 ssl http2;
	listen 10.1.0.1:443 ssl http2;
	server_name channelserver.fxa.mydomain.tld;

	### TLS
	include /etc/nginx/conf/00-tls-base.conf;
	ssl_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/fxa.mydomain.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/fxa.mydomain.tld/fullchain.pem;

	### ACL
	include conf/10-acl-mydomain.tld.conf;
	deny all;

	### Bots
	include /etc/nginx/bots.d/ddos.conf;
	include /etc/nginx/bots.d/blockbots.conf;

	### Paths
	location / {
		proxy_pass http://10.1.2.3:1234/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```

</p></details>
