### ISSUE TITLE
fxa-graphql-api_1 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by steffenweb** [jackyzy823/fxa-selfhosting#42]
Hello, i foollowed the instructions and got this error after I did run docker compose up:

```
 fxa-graphql-api_1                   | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
 fxa-graphql-api_1                   |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```

```
 os is Debian 12
 Docker version 28.1.1, build 4eba377
 docker-compose version 1.29.2, build unknown
```

config.yml:

```
 #! THIS FILE USING YTT(https://github.com/k14s/ytt/) FORMAT
 #! this is a general config for all related stuffs
 #@data/values
 ---
 #! Once config.yml changed you should rerun ./init.sh to regenerate `dest`/docker-compose.yml
 
 #! if PERSISTENCEPATH is relative, it relates to `dest`/docker-compose.yml
 persistencepath: .
 #! [WARNING] DO NOT DOWNGRADE WITHOUT A CLEAN DB SINCE SCHEMA CANNOT DOWNGRADE.
 
 #! latest tested version is : v1.305.0
 
 #! [NOTE] Pin mysql version to 8.4 to make server compatible with argument "mysql-native-password"
 #! [NOTE] You could also try my (upgraded) syncserver3 in Python3, No data integrity guaranteed!
 #! [NOTE] Since we use docker-compose-wait to build wait chain, so ./wait binary in dest folder is not necessary, you could delete it.
 #! [WORKAROUND] patch fxa-auth-server https://github.com/mozilla/fxa/issues/16491
 #! [NOTE] Although channelserver issue fixed , still using latest sha256 digest tag.
 #! [NOTE] don't use fxa version between 1.250.x to 1.258.x, https://github.com/mozilla/fxa/issues/15320
 #! [NOTE] from v1.242.4 mysql version upgrade to 8.0.16+
 #! [WORKAROUND] we use method 2 to to resolve below issue
 #! [ISSUE]  cannot change avatar due to https://github.com/mozilla/fxa/pull/7972 - checkAvatar - we have same domain with monogramUrl's one. issue: https://github.com/mozilla/fxa/issues/12426 
 #!          so either 1. use different domain like profile-img or 2. patch it 
 #! [WORKAROUND] add LASTACCESSTIME_UPDATES_SAMPLE_RATE=1 to make sync api/v1/account/devices not return 500. see https://github.com/mozilla/fxa/issues/12373
 #! [ISSUE][RESOLVED] v1.222.0 db-migration db connection need not workaround now.
 #! [WORKAROUD] v1.219.5 require smtp.user and smtp.pass (even not used) to make fxa-auth-server not send mail by AWS SES. (will cause a crash if AWS_ACCESS_KEY not set)
 #! [WORKAROUD] v1.215.4 workaround for 1. graphql-api's internal connection to fxa-auth-server (see debug.full_self_sign_workaround) and 2. db-migration db connection.
 #! [NOTE] from v1.215.2 mysql version upgrade to 5.7 . docker-compose requires supporting `service_completed_successfully`
 #! [ISSUE][RESOLVED] v1.196.0  oauth.domain.local/config return 404 causing syncserver fail to start.; fixed in https://github.com/mozilla/fxa/pull/7204
 #! [NOTE]from v1.192.0  all fxa docker's image are merge into mozilla/fxa-mono so it's a breaking change!
 #! [ISSUE][RESOLVED] v1.172.0 500 error after new-signup connect-another-device page maybe caused by https://github.com/mozilla/fxa/commit/2f9729154 ; fixed in https://github.com/mozilla/fxa/pull/5477
 #! [NOTE] v1.173+ change base docker image . missing key_*.json in fxa-auth-server so we change to branch br-v1.174.0 to apply breaking changes
 
 #! by default we use tested version , using latest at your own risk.
 fxa_version: "v1.305.0"
 option:
   sync:
     #! set true to keep all your sync items not expired
     neverexpire: false
   #! for device pairing
   channelserver:
     enable: true
   #! Since send is EOL , so use it at your own risk
   send:
     enable: false
     settings:
       #! settings are upperize to send ENV
       #! [TODO] send android , client_id 20f7931c9054d833
       fxa_client_id: "fced6b5e3f4c66b9"
       #![TODO] file_dir need volumes or not or ....
       max_file_size:
       #! for security and network bandwith/traffic sake , you'd better not  allow annoymous user to use your send in the internet
       #! see : https://www.zdnet.com/article/mozilla-suspends-firefox-send-service-while-it-addresses-malware-abuse/
       #! see https://portswigger.net/daily-swig/firefox-send-suspended-amid-concern-over-malware-abuse
       #! [NOTE] number 0 will be treated as false 
       anon_max_file_size: "0"
       #! expire_times_seconds array format "a,b,c"
       expire_times_seconds:
       default_expire_seconds:
       max_expire_seconds:
       anon_max_expire_seconds:
       max_downloads:
       anon_max_downloads:
       max_files_per_archive:
       max_archives_per_user:
       #! download_counts array format "a,b,c"
       download_counts:
   notes:
     enable: false
     settings:
       #! client_id is a must , depends on what you set in https://github.com/mozilla/notes/src/background.js
       #! client_id should equal to _init/auth/oauthserver-prod 
       client_id:
         webext: #! sample: "a3dbd8c5a6fd93e2"
         android: #! sample: "7f368c6886429f19"
   #!  According to https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/
   #!  since Firefox 79 ,it will use syncserver to replace kinto in webextension storage.sync API, so disabled by default
   #!  if you still want to use this , make about:config webextensions.storage.sync.kinto : true and webextensions.storage.sync.serverURL point to kinto domain name below
   webext_storagesync:
     enable: false
     settings:
       #! you shall not change this , "5882386c6d801776" means firefox
       client_id: "5882386c6d801776"
       #! [deprecated] fxa-oauth.clients.storagesync.client_id: "5882386c6d801776"
   #! last tested 13.6.3
   kinto_version: "latest"
   #! [TODO] intergate with kinto
   #! both with_notes and with_webext_storagesync need kinto server and it's postgres
   #! see kinto usage https://wiki.mozilla.org/Firefox/Kinto
   #! https://testpilot.settings.services.mozilla.com/v1/
   #! client_id 5882386c6d801776 == firefox
   #! https://webextensions.settings.services.mozilla.com/v1/
 #! [TODO] make docker-compose.tmp.yml data.values.domain.name and etc reusable via define
 #! domain name related stuff
 domain:
   #! base name
   name: "sync.xxxx.xxx"
   #! for content-server
   content: "www"
   auth: "api"
   oauth: "oauth"
   #! for profile server
   profile: "profile"
   #! for syncserver
   sync: "token"
   #! for graphql-api
   graphql: "graphql"
   #! must if option.channelserver.enable == true
   channelserver: "channelserver"
   #! for firefox send 
   #! must if option.send.enable == true
   send: "send"
   #! for notes and webextension storage.sync
   kinto: "kinto"
 nginx:
   #! port or ip/port or unix socket folder
   #! for those who want to reverse proxy ( and then we do not a host resolver ,because we just proxy_pass ip/port )
   #! can be a folder contains unix socket like "/var/run/fxa-selfhosing" with ssl = false and unix_socket = true- socket filename is nginx.sock
   #! make sure your reverse proxy have permission to access the folder.
   listener: "/var/run/fxa-selfhosting"
   #! set to true is `listener` is a unix socket
   unix_socket: true
   #! if false certs are not required and another fxa_nossl.conf is used
   #! set to false is `listener` is a unix socket
   ssl: false
   #! used if `ssl` is true
   certs:
     #! wild will only be used if detailed cert is not specified.
     #! certs location is absoulte or related to `dest`/docker-compose.yml
     #! cert can be self-signed with debug.full_self_sign_workaround: true. see more examples/full_selfsign.
     wild:
       cert: "./cert/wild.cer"
       key: "./cert/wild.key"
     content:
       cert: "./cert/content.cer"
       key: "./cert/content.key"
     auth:
       cert:
       key:
     oauth:
       cert:
       key:
     profile:
       cert:
       key:
     sync:
       cert:
       key:
     channelserver:
       cert:
       key:
     graphql:
       cert:
       key:
     send:
       cert:
       key:
     kinto:
       cert:
       key:
 mail:
   #! types are  "localhelper" ,  "localrelay" ,"3rd"
   #! smtp_user/smtp_pass is required for "localrelay" and "3rd" (can be any non-null string) even not used.
   #! "localhelper" uses fxa-auth-local-mail-helper which self sending and receiving and smtp_host/smtp_port/smtp_user/smtp_pass/smtp_secure do not affect.
   #!               mails are stored in memory , remeber to clean them (by DELETE api or restart container)
   #! "localrelay" use exim-sender  and smtp_host/smtp_port/smtp_user/smtp_pass/smtp_secure do not affect.
   #! "3rd"  send mail to 3rd (like gmail etc)
   type: "localhelper"
   #! for   "3rd": refer to your mail service provider
   smtp_host:
   smtp_port:
   smtp_user:
   smtp_pass:
   smtp_secure:
   #! if smtp_sender empty use "Firefox Accounts <no-reply@domain.name" default
   smtp_sender:
   #! only for "localhelper"
   #! web api
   localhelper:
     web: "127.0.0.1:9001"
 #! Here we can add some custom OAuth Client
 #! for example we add a OAuth Client which can read / write your sync data after granted by you
 oauth:
   clients:
   #! [NOTE] DO NOT ENABLE BELOW IF NOT USED
 #!  - id: deadbeafdeadbeaf
 #!    #! hex secret 0b2b91549678167e4870d76e2b94024b2954cb8605e4a2e8179ab80ecf40b287
 #!    hashedSecret: b88d5613f75ed5362ecb8c263be5b918aafbb23aac39f817eac44cbe4df7cda3
 #!    name: SyncManager
 #!    imageUri: ''
 #!    #! if generate_redirectUri will automatic generate redircturi : https://{content}.{domain_name}/oauth/success/{id}
 #!    generate_redirectUri: true
 #!    redirectUri: 
 #!    trusted: true
 #!    #! some explain https://github.com/mozilla/fxa/blob/96cbbccfaed1de93d556a2259554acfabeb4cbe5/packages/fxa-auth-server/lib/oauth/authorized_clients.js#L55
 #!    canGrant: true
 #!    publicClient: true
 #!    #! redirecturi will be add to contetserver.prod.tmp.yml if scope matches
 #!    #! allowedScopes is a space-seperated string
 #!    allowedScopes: https://identity.mozilla.com/apps/oldsync
 
 secrets:
   authsecret: "XXXXXXXXXXXXXX"
   flowidkey: "XXXXXXXXXXXXXXX"
   profileserver_authsecret_bearertoken: "XXXXXXXXXXXXXX"
 debug:
   #! for register preverifed account , we need to set fxa-auth-server 's NODE_ENV  not to be `prod`
   #! see  fxa-auth-server/lib/routes/account.js `delete routes[0].options.validate.payload.preVerified;`
   auth_server_preverifed: false
   deps_logs: false
   #! make a e2e test compose file
   #! require mail.type == localhelper
   e2e_test:
     enable: false
     #! only used when full_self_sign_workaroud == true
     root_cert:
   #! workaroud for fxa-graphql-api with full self sign
   #! if you want fxa-graphql-api communicate with fxa-auth-server internally , turn this `true`
   #! [WARN] browserid-verifier will not work. Since BrowserID is deprecated, just do not use old browser or python `syncclient`
   full_self_sign_workaround: false
   #! Use a [python3 version syncserver](https://github.com/jackyzy823/syncserver3)
   use_syncserver3: false
   #! for old docker-compose binary backward compatibility
   keep_compose_file_version_property: false

```
docker-compose.yml

```
 x-logging:
   options:
     max-size: 5m
     max-file: "3"
   driver: json-file
 services:
   mysqldb:
     image: mysql:8.4
     environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
     - MYSQL_ROOT_HOST=%
     expose:
     - "3306"
     volumes:
     - ./mysql_data:/var/lib/mysql/
     - ./_init/mysql/init.sql:/tmp/common_init.sql:ro
     logging:
       driver: none
     restart: unless-stopped
     command:
     - --event-scheduler=ON
     - --init-file=/tmp/common_init.sql
     - --authentication_policy=mysql_native_password
     - --mysql-native-password=ON
   redis:
     image: redis:6.0-alpine
     expose:
     - "6379"
     logging:
       driver: none
     volumes:
     - type: tmpfs
       target: /data
     restart: unless-stopped
   waitforinfra:
     image: ghcr.io/ufoscout/docker-compose-wait:2.12.1
     depends_on:
     - mysqldb
     - redis
     command: /wait
     environment:
     - WAIT_HOSTS=redis:6379,mysqldb:3306
     - WAIT_TIMEOUT=120
   waitfordeps:
     image: ghcr.io/ufoscout/docker-compose-wait:2.12.1
     depends_on:
     - fxa-auth-server
     - fxa-content-server
     command: /wait
     environment:
     - WAIT_HOSTS=fxa-auth-server:9000,fxa-content-server:3030
     - WAIT_TIMEOUT=120
   browseridverifier.local:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/browserid-verifier
     expose:
     - "5050"
     environment:
     - PORT=5050
     - IP_ADDRESS=0.0.0.0
     - FORCE_INSECURE_LOOKUP_OVER_HTTP=false
     - HTTP_TIMEOUT=60
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
     entrypoint: node
     command: server.js
   syncserver:
     image: mozilla/syncserver@sha256:016162bf39d8486d5710b4ae5bcaaebd8bd60b55db6cf468b8f720b526bd68b7
     expose:
     - "5000"
     environment:
     - SYNCSERVER_PUBLIC_URL=https://token.xxxxx.xxxx.xxx
     - SYNCSERVER_BROWSERID_VERIFIER=http://browseridverifier.local:5050
     - SYNCSERVER_SQLURI=mysql+pymysql://root@mysqldb/sync
     - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
     - SYNCSERVER_FORCE_WSGI_ENVIRON=true
     - PORT=5000
     - SYNCSERVER_OAUTH_VERIFIER=http://fxa-auth-server:9000
     - SYNCSERVER_IDENTITY_PROVIDER=http://fxa-content-server:3030
     depends_on:
       mysqldb:
         condition: service_started
       fxa-auth-server:
         condition: service_started
       fxa-content-server:
         condition: service_started
       waitforinfra:
         condition: service_completed_successfully
       waitfordeps:
         condition: service_completed_successfully
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-db-migrations:
     image: mozilla/fxa-mono:v1.305.0
     working_dir: /fxa/packages/db-migrations
     depends_on:
       mysqldb:
         condition: service_started
       waitforinfra:
         condition: service_completed_successfully
     command: sh -c "node ./bin/patcher.mjs"
     environment:
     - AUTH_MYSQL_HOST=mysqldb
     - PROFILE_MYSQL_HOST=mysqldb
     - OAUTH_MYSQL_HOST=mysqldb
     - PUSHBOX_MYSQL_HOST=mysqldb
     restart: "no"
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-auth-local-mail-helper:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/fxa-auth-server/dist/packages/fxa-auth-server
     expose:
     - "9999"
     ports:
     - 127.0.0.1:9001:9001
     environment:
     - NODE_ENV=dev
     - SMTP_PORT=9999
     - MAILER_HOST=0.0.0.0
     - MAILER_PORT=9001
     - REDIS_HOST=redis
     command: sh -c "mkdir -p test && cd test && cp /fxa/packages/fxa-auth-server/test/mail_helper.js
       . && npm init --yes && npm i mailparser@0.6.1 simplesmtp && node mail_helper.js"
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
     depends_on:
       waitforinfra:
         condition: service_completed_successfully
   fxa-auth-server:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/fxa-auth-server/dist/packages/fxa-auth-server
     expose:
     - "9000"
     depends_on:
       redis:
         condition: service_started
       mysqldb:
         condition: service_started
       waitforinfra:
         condition: service_completed_successfully
       fxa-db-migrations:
         condition: service_completed_successfully
     volumes:
     - ./_init/auth/oauthserver-prod.json:/fxa/packages/fxa-auth-server/dist/packages/fxa-auth-server/config/prod.json
     environment:
     - OAUTH_SERVER_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXX
     - OAUTH_SERVER_SECRETS=XXXXXXXXXXXXXXXXXXXXX
     - AUTH_SERVER_SHARED_SECRET=XXXXXXXXXXXXXXXXXXXXX
     - AUTH_SERVER_SECRETS=XXXXXXXXXXXXXXXXXXXXX,realwhatever
     - PROFILE_SERVER_AUTH_SECRET_BEARER_TOKEN=XXXXXXXXXXXXXXXXXXXXX
     - FLOW_ID_KEY=KoQJ49zuAo9bKjleyyqB
     - REDIS_HOST=redis
     - ACCESS_TOKEN_REDIS_HOST=redis
     - REFRESH_TOKEN_REDIS_HOST=redis
     - CUSTOMS_REDIS_HOST=redis
     - METRICS_REDIS_HOST=redis
     - AUTH_CACHE_REDIS_HOST=redis
     - RECOVERY_PHONE_REDIS_HOST=redis
     - SNS_TOPIC_ARN=disabled
     - DB=mysql
     - MYSQL_HOST=mysqldb
     - AUTH_MYSQL_HOST=mysqldb
     - IP_ADDRESS=0.0.0.0
     - SIGNIN_UNBLOCK_FORCED_EMAILS=^block.*@restmail\\.net$$
     - SIGNIN_CONFIRMATION_ENABLED=true
     - SIGNIN_CONFIRMATION_FORCE_EMAIL_REGEX=^sync.*@restmail\\.net$$
     - ISSUER=api.xxxxx.xxxx.xxx
     - PUBLIC_URL=https://api.xxxxx.xxxx.xxx
     - OAUTH_URL=https://oauth.xxxxx.xxxx.xxx
     - CONTENT_URL=https://www.xxxxx.xxxx.xxx
     - CONTENT_SERVER_URL=https://www.xxxxx.xxxx.xxx
     - SYNC_TOKENSERVER_URL=https://token.xxxxx.xxxx.xxx/token
     - PROFILE_SERVER_URL=http://fxa-profile-server:1111
     - FXA_OPENID_ISSUER=https://www.xxxxx.xxxx.xxx
     - VERIFICATION_URL=http://browseridverifier.local:5050/v2
     - PUSHBOX_ENABLED=true
     - PUSHBOX_MAX_TTL=12 months
     - PUSHBOX_MYSQL_HOST=mysqldb
     - CUSTOMS_SERVER_URL=none
     - FXA_OPENID_KEYFILE=config/key.json
     - FXA_OPENID_NEWKEYFILE=config/newKey.json
     - FXA_OPENID_OLDKEYFILE=config/oldKey.json
     - SMTP_SENDER=Firefox Accounts <no-reply@xxxxx.xxxx.xxx
     - SMTP_HOST=fxa-auth-local-mail-helper
     - SMTP_PORT=9999
     - SMTP_USER=local
     - SMTP_PASS=local
     - GEODB_ENABLED=false
     - LOG_LEVEL=WARN
     - LASTACCESSTIME_UPDATES_SAMPLE_RATE=1
     - ACCOUNT_EVENTS_ENABLED=false
     - FXA_EXPIRATION_ACCESS_TOKEN=7 days
     - AUTH_GLEAN_ENABLED=false
     command: |
       sh -c "( sed -i 's_@fxa/shared/pem-jwk_../../../libs/shared/pem-jwk/src/index.js_' scripts/gen_keys.js && node scripts/gen_keys.js ); node scripts/oauth_gen_keys.js ; node scripts/gen_vapid_keys.js  && sed -i '/increment/a histogram: () = { },' bin/key_server.js && node bin/key_server.js"
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-profile-static:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/fxa-profile-server
     volumes:
     - ./public:/fxa/packages/fxa-profile-server/var/public/:ro
     expose:
     - "1112"
     environment:
     - HOST=0.0.0.0
     - IMG=local
     command:
     - node
     - bin/_static.js
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-profile-worker-make-writable:
     image: mozilla/fxa-mono:v1.305.0
     user: root
     volumes:
     - ./public:/fxa/packages/fxa-profile-server/var/public/
     command:
     - chmod
     - a+w
     - /fxa/packages/fxa-profile-server/var/public/
     restart: "no"
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-profile-worker:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/fxa-profile-server
     volumes:
     - ./public:/fxa/packages/fxa-profile-server/var/public/
     expose:
     - "1113"
     environment:
     - WORKER_HOST=0.0.0.0
     - IMG=local
     depends_on:
       fxa-profile-worker-make-writable:
         condition: service_completed_successfully
     command:
     - node
     - bin/worker.js
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-profile-server:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/fxa-profile-server
     volumes:
     - ./public:/fxa/packages/fxa-profile-server/var/public/
     expose:
     - "1111"
     depends_on:
       mysqldb:
         condition: service_started
       redis:
         condition: service_started
       waitforinfra:
         condition: service_completed_successfully
       fxa-db-migrations:
         condition: service_completed_successfully
     environment:
     - AUTH_SECRET_BEARER_TOKEN=XXXXXXXXXXXXXXXXXXXXX
     - EVENTS_ENABLED=false
     - HOST=0.0.0.0
     - DB=mysql
     - IMG_PROVIDERS_FXA=^https://profile.xxxxx.xxxx.xxx/img/a/[0-9a-f]{32}$$
     - IMG_URL=https://profile.xxxxx.xxxx.xxx/img/a/{id}
     - PUBLIC_URL=https://profile.xxxxx.xxxx.xxx
     - MYSQL_HOST=mysqldb
     - IMG=local
     - AUTH_SERVER_URL=http://fxa-auth-server:9000/v1
     - OAUTH_SERVER_URL=http://fxa-auth-server:9000/v1
     - REDIS_HOST=redis
     - WORKER_URL=http://fxa-profile-worker:1113
     command: sh -c "sed -i 's|result.avatar.startsWith(monogramUrl)|result.avatar.startsWith(`$${monogramUrl}/v1/avatar/`)|'  /fxa/packages/fxa-profile-server/lib/routes/profile.js
       && node bin/server.js"
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-content-server:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/fxa-content-server
     expose:
     - "3030"
     depends_on:
     - fxa-auth-server
     - fxa-profile-server
     - redis
     volumes:
     - ./_init/content/contentserver-prod.json:/fxa/packages/fxa-content-server/config/prod.json
     environment:
     - CONFIG_FILES=/fxa/packages/fxa-content-server/config/prod.json
     - FXA_OAUTH_CLIENT_ID=ea3ca969f8c6bb0d
     - FLOW_ID_KEY=KoQJ49zuAo9bKjleyyqB
     - FEATURE_FLAGS_REDIS_HOST=redis
     - SYNC_TOKENSERVER_URL=https://token.xxxxx.xxxx.xxx/token
     - PUBLIC_URL=https://www.xxxxx.xxxx.xxx
     - FXA_OAUTH_URL=https://oauth.xxxxx.xxxx.xxx
     - FXA_URL=https://api.xxxxx.xxxx.xxx
     - FXA_PROFILE_URL=https://profile.xxxxx.xxxx.xxx
     - FXA_PROFILE_IMAGES_URL=https://profile.xxxxx.xxxx.xxx
     - PAIRING_SERVER_BASE_URI=wss://channelserver.xxxxx.xxxx.xxx
     - FXA_MARKETING_EMAIL_ENABLED=false
     - GEODB_ENABLED=false
     - LOG_LEVEL=WARN
     - NODE_ENV=production
     - STATIC_DIRECTORY=dist
     - PAGE_TEMPLATE_SUBDIRECTORY=dist
     - CSP_ENABLED=true
     - FXA_MX_RECORD_VALIDATION=false
     - FXA_GQL_URL=https://graphql.xxxxx.xxxx.xxx
     - REDIRECT_CHECK_ALLOW_LIST=*.xxxxx.xxxx.xxx
     - APPLE_AUTH_ENABLED=false
     - GOOGLE_AUTH_ENABLED=false
     - GLEAN_ENEABLED=false
     - GLEAN_UPLOAD_ENABLED=false
     - GLEAN_LOG_PINGS=false
     - CONTENT_SERVER_GLEAN_ENABLED=false
     - REACT_CONVERSION_SIGNUP_ROUTES=true
     - REACT_CONVERSION_SIGNIN_ROUTES=true
     - REACT_CONVERSION_SIMPLE_ROUTES=true
     - REACT_CONVERSION_RESET_PASSWORD_ROUTES=true
     - REACT_CONVERSION_POST_VERIFY_THIRD_PARTY_AUTH=true
     command:
     - /bin/sh
     - -c
     - |
       sed -i "s|https://cdn.accounts.firefox.com|$${PUBLIC_URL}|g" ./dist/settings/prod/asset-manifest.json ./dist/settings/prod/index.html ./dist/settings/prod/static/js/main.* &&
       node server/bin/fxa-content-server.js
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   fxa-graphql-api:
     image: mozilla/fxa-mono:v1.305.0
     stop_grace_period: 1s
     working_dir: /fxa/packages/fxa-graphql-api/dist/packages/fxa-graphql-api
     expose:
     - "8290"
     depends_on:
       fxa-auth-server:
         condition: service_started
       fxa-profile-server:
         condition: service_started
       redis:
         condition: service_started
       mysqldb:
         condition: service_started
       waitforinfra:
         condition: service_completed_successfully
     environment:
     - ACCESS_TOKEN_REDIS_HOST=redis
     - PROFILE_SERVER_URL=http://fxa-profile-server:1111/v1
     - CUSTOMS_SERVER_URL=none
     - CORS_ORIGIN=https://www.xxxxx.xxxx.xxx
     - AUTH_SERVER_URL=https://api.xxxxx.xxxx.xxx/v1
     - SETTINGS_SERVER_URL=http://fxa-content-server:3030
     - AUTH_MYSQL_HOST=mysqldb
     - PROFILE_MYSQL_HOST=mysqldb
     - OAUTH_MYSQL_HOST=mysqldb
     - SNS_TOPIC_ARN=disabled
     - SNS_TOPIC_ENDPOINT=disabled
     - CONFIG_FILES=/fxa/packages/fxa-graphql-api/dist/packages/fxa-graphql-api/src/config/production.json
     command: sh -c "node src/main.js"
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file
   nginx:
     image: nginx:1.22.0-alpine
     depends_on:
     - fxa-auth-server
     - fxa-profile-server
     - syncserver
     - fxa-content-server
     - fxa-graphql-api
     - channelserver
     volumes:
     - ./_init/nginx/fxa_nossl.conf.tmpl:/etc/nginx/templates/fxa.conf.tmpl:ro
     - ./_init/nginx/channelserver_nossl.conf.tmpl:/etc/nginx/templates/channelserver.conf.tmpl:ro
     - /var/run/fxa-selfhosting:/var/run/fxa
     environment:
     - NGINX_LISTENER=unix:/var/run/fxa/nginx.sock
     - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.tmpl
     - NGINX_DOMAIN_NAME=xxxxx.xxxx.xxx
     - CONTENT=www
     - AUTH=api
     - OAUTH=oauth
     - PROFILE=profile
     - SYNC=token
     - GRAPHQL=graphql
     - CHANNELSERVER=channelserver
     logging:
       driver: none
     restart: unless-stopped
   channelserver:
     image: mozilla/channelserver@sha256:e0b4f3c2afa54cdc4d484edf44e4517bf6d9a6dc1e71a1b4986ac0c5e28620a4
     expose:
     - "8000"
     restart: unless-stopped
     logging:
       options:
         max-size: 5m
         max-file: "3"
       driver: json-file

```
