### ISSUE TITLE
Empty user/password in smpt config is replace by "none" value in docker compose

### ISSUE THREAD

**Issue by poofyteddy** [jackyzy823/fxa-selfhosting#5]
Hi,
A quick thing i found while trying to get the mail part working.
if you setup 3rd party smtp email in the config.py to use unencrypted and anonymous connection (aka no user or password), the field in the docker-compose file are replaced by "none" after running the script.
```
mail:
  #! types are  "localhelper" ,  "localrelay" ,"3rd"
  #! "localhelper" uses fxa-auth-local-mail-helper which self sending and receiving and smtp_host/smtp_port/smtp_user/smtp_pass/smtp_secure do not affect.
  #! "localrelay" use exim-sender  and smtp_host/smtp_port/smtp_user/smtp_pass/smtp_secure do not affect.
  #! "3rd"  send mail to 3rd (like gmail etc)
  type: "3rd"
  #! for   "3rd": refer to your mail service provider
  smtp_host: mailserver.domain.com
  smtp_port: 25
  smtp_user:
  smtp_pass:
  smtp_secure: false
```
translate to
```
    - SMTP_HOST=mailserver.domain.com
    - SMTP_PORT=25
    - SMTP_USER=None
    - SMTP_PASS=None
    - SMTP_SECURE=False
    - GEODB_ENABLED=false
```
but should be 
```
    - SMTP_HOST=mailserver.domain.com
    - SMTP_PORT=25
    - SMTP_USER=
    - SMTP_PASS=
    - SMTP_SECURE=False
    - GEODB_ENABLED=false
```
Thank for the hard work
