### ISSUE TITLE
cannot use docker compose up

### ISSUE THREAD

**Issue by coucoy** [jackyzy823/fxa-selfhosting#9]
Hi, when i do compose up i get the following error:
   services.pushbox.local.environment.2 must be a string

this is the section of the config affected
```
  pushbox.local: #!  used by fxa-auth-server
  #!  a tld-like name is required for fxa-auth-server config's url type check
  #!  note manually delete old data? -> Done via _init/mysql/init.sql -> create event
  #!  see:  https://github.com/mozilla-services/pushbox#! database
  #!  DELETE from pushboxv1 where TTL < unix_timestamp();
    image: mozilla/pushbox:0.3.0 #!  if latest not work please specific :0.3.0 (last tested version)
    expose:
      - "8002"
    environment:
      - ROCKET_ENV=prod

      - ROCKET_PORT=8002
      #!  should same as fxa-auth-server -> pushbox->key
      - #@ "ROCKET_SERVER_TOKEN={pushboxkey}".format(pushboxkey=data.values.secrets.pushboxkey)
      - ROCKET_DATABASE_URL=mysql://root@mysqldb/pushbox
      - WAIT_HOSTS=mysqldb:3306
      - WAIT_HOSTS_TIMEOUT=120
    depends_on:
      - mysqldb
    volumes:
      - ./wait:/wait
    command: sh -c "/wait && /app/bin/pushbox"
    restart: unless-stopped
    logging: *default-logging
```
